// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: KWellLog.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tet.Kindom {

  /// <summary>Holder for reflection information generated from KWellLog.proto</summary>
  public static partial class KWellLogReflection {

    #region Descriptor
    /// <summary>File descriptor for KWellLog.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static KWellLogReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5LV2VsbExvZy5wcm90bxIKVGV0LktpbmRvbSLhAQoIS1dlbGxMb2cSDgoG",
            "d2VsbGlkGAEgASgJEhAKCHdlbGxuYW1lGAIgASgJEhEKCWN1cnZlbmFtZRgD",
            "IAEoCRIRCgljdXJ2ZXR5cGUYBCABKAkSDAoEdW5pdBgFIAEoCRITCgtzYW1w",
            "bGVfcmF0ZRgGIAEoARIPCgdtaW5pbXVtGAcgASgBEg8KB21heGltdW0YCCAB",
            "KAESDwoHYXZlcmFnZRgJIAEoARITCgtzdGFydF9kZXB0aBgKIAEoARIRCgll",
            "bmRfZGVwdGgYCyABKAESDwoHc2FtcGxlcxgMIAMoASIzCgxLV2VsbExvZ0xp",
            "c3QSIwoFSXRlbXMYASADKAsyFC5UZXQuS2luZG9tLktXZWxsTG9nYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tet.Kindom.KWellLog), global::Tet.Kindom.KWellLog.Parser, new[]{ "Wellid", "Wellname", "Curvename", "Curvetype", "Unit", "SampleRate", "Minimum", "Maximum", "Average", "StartDepth", "EndDepth", "Samples" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tet.Kindom.KWellLogList), global::Tet.Kindom.KWellLogList.Parser, new[]{ "Items" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class KWellLog : pb::IMessage<KWellLog>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<KWellLog> _parser = new pb::MessageParser<KWellLog>(() => new KWellLog());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<KWellLog> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tet.Kindom.KWellLogReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KWellLog() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KWellLog(KWellLog other) : this() {
      wellid_ = other.wellid_;
      wellname_ = other.wellname_;
      curvename_ = other.curvename_;
      curvetype_ = other.curvetype_;
      unit_ = other.unit_;
      sampleRate_ = other.sampleRate_;
      minimum_ = other.minimum_;
      maximum_ = other.maximum_;
      average_ = other.average_;
      startDepth_ = other.startDepth_;
      endDepth_ = other.endDepth_;
      samples_ = other.samples_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KWellLog Clone() {
      return new KWellLog(this);
    }

    /// <summary>Field number for the "wellid" field.</summary>
    public const int WellidFieldNumber = 1;
    private string wellid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Wellid {
      get { return wellid_; }
      set {
        wellid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "wellname" field.</summary>
    public const int WellnameFieldNumber = 2;
    private string wellname_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Wellname {
      get { return wellname_; }
      set {
        wellname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "curvename" field.</summary>
    public const int CurvenameFieldNumber = 3;
    private string curvename_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Curvename {
      get { return curvename_; }
      set {
        curvename_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "curvetype" field.</summary>
    public const int CurvetypeFieldNumber = 4;
    private string curvetype_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Curvetype {
      get { return curvetype_; }
      set {
        curvetype_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "unit" field.</summary>
    public const int UnitFieldNumber = 5;
    private string unit_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Unit {
      get { return unit_; }
      set {
        unit_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sample_rate" field.</summary>
    public const int SampleRateFieldNumber = 6;
    private double sampleRate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double SampleRate {
      get { return sampleRate_; }
      set {
        sampleRate_ = value;
      }
    }

    /// <summary>Field number for the "minimum" field.</summary>
    public const int MinimumFieldNumber = 7;
    private double minimum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Minimum {
      get { return minimum_; }
      set {
        minimum_ = value;
      }
    }

    /// <summary>Field number for the "maximum" field.</summary>
    public const int MaximumFieldNumber = 8;
    private double maximum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Maximum {
      get { return maximum_; }
      set {
        maximum_ = value;
      }
    }

    /// <summary>Field number for the "average" field.</summary>
    public const int AverageFieldNumber = 9;
    private double average_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Average {
      get { return average_; }
      set {
        average_ = value;
      }
    }

    /// <summary>Field number for the "start_depth" field.</summary>
    public const int StartDepthFieldNumber = 10;
    private double startDepth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double StartDepth {
      get { return startDepth_; }
      set {
        startDepth_ = value;
      }
    }

    /// <summary>Field number for the "end_depth" field.</summary>
    public const int EndDepthFieldNumber = 11;
    private double endDepth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double EndDepth {
      get { return endDepth_; }
      set {
        endDepth_ = value;
      }
    }

    /// <summary>Field number for the "samples" field.</summary>
    public const int SamplesFieldNumber = 12;
    private static readonly pb::FieldCodec<double> _repeated_samples_codec
        = pb::FieldCodec.ForDouble(98);
    private readonly pbc::RepeatedField<double> samples_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<double> Samples {
      get { return samples_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as KWellLog);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(KWellLog other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Wellid != other.Wellid) return false;
      if (Wellname != other.Wellname) return false;
      if (Curvename != other.Curvename) return false;
      if (Curvetype != other.Curvetype) return false;
      if (Unit != other.Unit) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(SampleRate, other.SampleRate)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Minimum, other.Minimum)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Maximum, other.Maximum)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Average, other.Average)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(StartDepth, other.StartDepth)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(EndDepth, other.EndDepth)) return false;
      if(!samples_.Equals(other.samples_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Wellid.Length != 0) hash ^= Wellid.GetHashCode();
      if (Wellname.Length != 0) hash ^= Wellname.GetHashCode();
      if (Curvename.Length != 0) hash ^= Curvename.GetHashCode();
      if (Curvetype.Length != 0) hash ^= Curvetype.GetHashCode();
      if (Unit.Length != 0) hash ^= Unit.GetHashCode();
      if (SampleRate != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(SampleRate);
      if (Minimum != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Minimum);
      if (Maximum != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Maximum);
      if (Average != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Average);
      if (StartDepth != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(StartDepth);
      if (EndDepth != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(EndDepth);
      hash ^= samples_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Wellid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Wellid);
      }
      if (Wellname.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Wellname);
      }
      if (Curvename.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Curvename);
      }
      if (Curvetype.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Curvetype);
      }
      if (Unit.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Unit);
      }
      if (SampleRate != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(SampleRate);
      }
      if (Minimum != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(Minimum);
      }
      if (Maximum != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(Maximum);
      }
      if (Average != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(Average);
      }
      if (StartDepth != 0D) {
        output.WriteRawTag(81);
        output.WriteDouble(StartDepth);
      }
      if (EndDepth != 0D) {
        output.WriteRawTag(89);
        output.WriteDouble(EndDepth);
      }
      samples_.WriteTo(output, _repeated_samples_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Wellid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Wellid);
      }
      if (Wellname.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Wellname);
      }
      if (Curvename.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Curvename);
      }
      if (Curvetype.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Curvetype);
      }
      if (Unit.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Unit);
      }
      if (SampleRate != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(SampleRate);
      }
      if (Minimum != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(Minimum);
      }
      if (Maximum != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(Maximum);
      }
      if (Average != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(Average);
      }
      if (StartDepth != 0D) {
        output.WriteRawTag(81);
        output.WriteDouble(StartDepth);
      }
      if (EndDepth != 0D) {
        output.WriteRawTag(89);
        output.WriteDouble(EndDepth);
      }
      samples_.WriteTo(ref output, _repeated_samples_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Wellid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Wellid);
      }
      if (Wellname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Wellname);
      }
      if (Curvename.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Curvename);
      }
      if (Curvetype.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Curvetype);
      }
      if (Unit.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Unit);
      }
      if (SampleRate != 0D) {
        size += 1 + 8;
      }
      if (Minimum != 0D) {
        size += 1 + 8;
      }
      if (Maximum != 0D) {
        size += 1 + 8;
      }
      if (Average != 0D) {
        size += 1 + 8;
      }
      if (StartDepth != 0D) {
        size += 1 + 8;
      }
      if (EndDepth != 0D) {
        size += 1 + 8;
      }
      size += samples_.CalculateSize(_repeated_samples_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(KWellLog other) {
      if (other == null) {
        return;
      }
      if (other.Wellid.Length != 0) {
        Wellid = other.Wellid;
      }
      if (other.Wellname.Length != 0) {
        Wellname = other.Wellname;
      }
      if (other.Curvename.Length != 0) {
        Curvename = other.Curvename;
      }
      if (other.Curvetype.Length != 0) {
        Curvetype = other.Curvetype;
      }
      if (other.Unit.Length != 0) {
        Unit = other.Unit;
      }
      if (other.SampleRate != 0D) {
        SampleRate = other.SampleRate;
      }
      if (other.Minimum != 0D) {
        Minimum = other.Minimum;
      }
      if (other.Maximum != 0D) {
        Maximum = other.Maximum;
      }
      if (other.Average != 0D) {
        Average = other.Average;
      }
      if (other.StartDepth != 0D) {
        StartDepth = other.StartDepth;
      }
      if (other.EndDepth != 0D) {
        EndDepth = other.EndDepth;
      }
      samples_.Add(other.samples_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Wellid = input.ReadString();
            break;
          }
          case 18: {
            Wellname = input.ReadString();
            break;
          }
          case 26: {
            Curvename = input.ReadString();
            break;
          }
          case 34: {
            Curvetype = input.ReadString();
            break;
          }
          case 42: {
            Unit = input.ReadString();
            break;
          }
          case 49: {
            SampleRate = input.ReadDouble();
            break;
          }
          case 57: {
            Minimum = input.ReadDouble();
            break;
          }
          case 65: {
            Maximum = input.ReadDouble();
            break;
          }
          case 73: {
            Average = input.ReadDouble();
            break;
          }
          case 81: {
            StartDepth = input.ReadDouble();
            break;
          }
          case 89: {
            EndDepth = input.ReadDouble();
            break;
          }
          case 98:
          case 97: {
            samples_.AddEntriesFrom(input, _repeated_samples_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Wellid = input.ReadString();
            break;
          }
          case 18: {
            Wellname = input.ReadString();
            break;
          }
          case 26: {
            Curvename = input.ReadString();
            break;
          }
          case 34: {
            Curvetype = input.ReadString();
            break;
          }
          case 42: {
            Unit = input.ReadString();
            break;
          }
          case 49: {
            SampleRate = input.ReadDouble();
            break;
          }
          case 57: {
            Minimum = input.ReadDouble();
            break;
          }
          case 65: {
            Maximum = input.ReadDouble();
            break;
          }
          case 73: {
            Average = input.ReadDouble();
            break;
          }
          case 81: {
            StartDepth = input.ReadDouble();
            break;
          }
          case 89: {
            EndDepth = input.ReadDouble();
            break;
          }
          case 98:
          case 97: {
            samples_.AddEntriesFrom(ref input, _repeated_samples_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class KWellLogList : pb::IMessage<KWellLogList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<KWellLogList> _parser = new pb::MessageParser<KWellLogList>(() => new KWellLogList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<KWellLogList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tet.Kindom.KWellLogReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KWellLogList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KWellLogList(KWellLogList other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KWellLogList Clone() {
      return new KWellLogList(this);
    }

    /// <summary>Field number for the "Items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Tet.Kindom.KWellLog> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::Tet.Kindom.KWellLog.Parser);
    private readonly pbc::RepeatedField<global::Tet.Kindom.KWellLog> items_ = new pbc::RepeatedField<global::Tet.Kindom.KWellLog>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Tet.Kindom.KWellLog> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as KWellLogList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(KWellLogList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      items_.WriteTo(ref output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(KWellLogList other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
