// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: well_log_object.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tet.Transport.Protobuf.Well {

  /// <summary>Holder for reflection information generated from well_log_object.proto</summary>
  public static partial class WellLogObjectReflection {

    #region Descriptor
    /// <summary>File descriptor for well_log_object.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WellLogObjectReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChV3ZWxsX2xvZ19vYmplY3QucHJvdG8SG1RldC5UcmFuc3BvcnQuUHJvdG9i",
            "dWYuV2VsbBoeZ29vZ2xlL3Byb3RvYnVmL3dyYXBwZXJzLnByb3RvIr8CChVQ",
            "YldlbGxMb2dDcmVhdGVQYXJhbXMSDwoHd2VsbF9pZBgBIAEoAxITCgtkYXRh",
            "X3NldF9pZBgCIAEoAxISCgpjdXJ2ZV9uYW1lGAMgASgJEhMKC3NhbXBsZV9y",
            "YXRlGAQgASgBEhMKC3N0YXJ0X2RlcHRoGAUgASgBEhIKCmN1cnZlX3R5cGUY",
            "BiABKAkSNgoRc2FtcGxlX21lYXR1cmVfaWQYByABKAsyGy5nb29nbGUucHJv",
            "dG9idWYuSW50MzJWYWx1ZRIzCg5zYW1wbGVfdW5pdF9pZBgIIAEoCzIbLmdv",
            "b2dsZS5wcm90b2J1Zi5JbnQzMlZhbHVlEjAKCm51bGxfdmFsdWUYCSABKAsy",
            "HC5nb29nbGUucHJvdG9idWYuRG91YmxlVmFsdWUSDwoHc2FtcGxlcxgKIAMo",
            "ASJbChNQYldlbGxMb2dDcmVhdGVMaXN0EkQKCGxvZ19saXN0GAEgAygLMjIu",
            "VGV0LlRyYW5zcG9ydC5Qcm90b2J1Zi5XZWxsLlBiV2VsbExvZ0NyZWF0ZVBh",
            "cmFtc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tet.Transport.Protobuf.Well.PbWellLogCreateParams), global::Tet.Transport.Protobuf.Well.PbWellLogCreateParams.Parser, new[]{ "WellId", "DataSetId", "CurveName", "SampleRate", "StartDepth", "CurveType", "SampleMeatureId", "SampleUnitId", "NullValue", "Samples" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tet.Transport.Protobuf.Well.PbWellLogCreateList), global::Tet.Transport.Protobuf.Well.PbWellLogCreateList.Parser, new[]{ "LogList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PbWellLogCreateParams : pb::IMessage<PbWellLogCreateParams>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PbWellLogCreateParams> _parser = new pb::MessageParser<PbWellLogCreateParams>(() => new PbWellLogCreateParams());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PbWellLogCreateParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tet.Transport.Protobuf.Well.WellLogObjectReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbWellLogCreateParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbWellLogCreateParams(PbWellLogCreateParams other) : this() {
      wellId_ = other.wellId_;
      dataSetId_ = other.dataSetId_;
      curveName_ = other.curveName_;
      sampleRate_ = other.sampleRate_;
      startDepth_ = other.startDepth_;
      curveType_ = other.curveType_;
      SampleMeatureId = other.SampleMeatureId;
      SampleUnitId = other.SampleUnitId;
      NullValue = other.NullValue;
      samples_ = other.samples_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbWellLogCreateParams Clone() {
      return new PbWellLogCreateParams(this);
    }

    /// <summary>Field number for the "well_id" field.</summary>
    public const int WellIdFieldNumber = 1;
    private long wellId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long WellId {
      get { return wellId_; }
      set {
        wellId_ = value;
      }
    }

    /// <summary>Field number for the "data_set_id" field.</summary>
    public const int DataSetIdFieldNumber = 2;
    private long dataSetId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long DataSetId {
      get { return dataSetId_; }
      set {
        dataSetId_ = value;
      }
    }

    /// <summary>Field number for the "curve_name" field.</summary>
    public const int CurveNameFieldNumber = 3;
    private string curveName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CurveName {
      get { return curveName_; }
      set {
        curveName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sample_rate" field.</summary>
    public const int SampleRateFieldNumber = 4;
    private double sampleRate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double SampleRate {
      get { return sampleRate_; }
      set {
        sampleRate_ = value;
      }
    }

    /// <summary>Field number for the "start_depth" field.</summary>
    public const int StartDepthFieldNumber = 5;
    private double startDepth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double StartDepth {
      get { return startDepth_; }
      set {
        startDepth_ = value;
      }
    }

    /// <summary>Field number for the "curve_type" field.</summary>
    public const int CurveTypeFieldNumber = 6;
    private string curveType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CurveType {
      get { return curveType_; }
      set {
        curveType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sample_meature_id" field.</summary>
    public const int SampleMeatureIdFieldNumber = 7;
    private static readonly pb::FieldCodec<int?> _single_sampleMeatureId_codec = pb::FieldCodec.ForStructWrapper<int>(58);
    private int? sampleMeatureId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int? SampleMeatureId {
      get { return sampleMeatureId_; }
      set {
        sampleMeatureId_ = value;
      }
    }


    /// <summary>Field number for the "sample_unit_id" field.</summary>
    public const int SampleUnitIdFieldNumber = 8;
    private static readonly pb::FieldCodec<int?> _single_sampleUnitId_codec = pb::FieldCodec.ForStructWrapper<int>(66);
    private int? sampleUnitId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int? SampleUnitId {
      get { return sampleUnitId_; }
      set {
        sampleUnitId_ = value;
      }
    }


    /// <summary>Field number for the "null_value" field.</summary>
    public const int NullValueFieldNumber = 9;
    private static readonly pb::FieldCodec<double?> _single_nullValue_codec = pb::FieldCodec.ForStructWrapper<double>(74);
    private double? nullValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double? NullValue {
      get { return nullValue_; }
      set {
        nullValue_ = value;
      }
    }


    /// <summary>Field number for the "samples" field.</summary>
    public const int SamplesFieldNumber = 10;
    private static readonly pb::FieldCodec<double> _repeated_samples_codec
        = pb::FieldCodec.ForDouble(82);
    private readonly pbc::RepeatedField<double> samples_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> Samples {
      get { return samples_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PbWellLogCreateParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PbWellLogCreateParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WellId != other.WellId) return false;
      if (DataSetId != other.DataSetId) return false;
      if (CurveName != other.CurveName) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(SampleRate, other.SampleRate)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(StartDepth, other.StartDepth)) return false;
      if (CurveType != other.CurveType) return false;
      if (SampleMeatureId != other.SampleMeatureId) return false;
      if (SampleUnitId != other.SampleUnitId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableDoubleEqualityComparer.Equals(NullValue, other.NullValue)) return false;
      if(!samples_.Equals(other.samples_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (WellId != 0L) hash ^= WellId.GetHashCode();
      if (DataSetId != 0L) hash ^= DataSetId.GetHashCode();
      if (CurveName.Length != 0) hash ^= CurveName.GetHashCode();
      if (SampleRate != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(SampleRate);
      if (StartDepth != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(StartDepth);
      if (CurveType.Length != 0) hash ^= CurveType.GetHashCode();
      if (sampleMeatureId_ != null) hash ^= SampleMeatureId.GetHashCode();
      if (sampleUnitId_ != null) hash ^= SampleUnitId.GetHashCode();
      if (nullValue_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableDoubleEqualityComparer.GetHashCode(NullValue);
      hash ^= samples_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (WellId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(WellId);
      }
      if (DataSetId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(DataSetId);
      }
      if (CurveName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CurveName);
      }
      if (SampleRate != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(SampleRate);
      }
      if (StartDepth != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(StartDepth);
      }
      if (CurveType.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CurveType);
      }
      if (sampleMeatureId_ != null) {
        _single_sampleMeatureId_codec.WriteTagAndValue(output, SampleMeatureId);
      }
      if (sampleUnitId_ != null) {
        _single_sampleUnitId_codec.WriteTagAndValue(output, SampleUnitId);
      }
      if (nullValue_ != null) {
        _single_nullValue_codec.WriteTagAndValue(output, NullValue);
      }
      samples_.WriteTo(output, _repeated_samples_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (WellId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(WellId);
      }
      if (DataSetId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(DataSetId);
      }
      if (CurveName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CurveName);
      }
      if (SampleRate != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(SampleRate);
      }
      if (StartDepth != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(StartDepth);
      }
      if (CurveType.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CurveType);
      }
      if (sampleMeatureId_ != null) {
        _single_sampleMeatureId_codec.WriteTagAndValue(ref output, SampleMeatureId);
      }
      if (sampleUnitId_ != null) {
        _single_sampleUnitId_codec.WriteTagAndValue(ref output, SampleUnitId);
      }
      if (nullValue_ != null) {
        _single_nullValue_codec.WriteTagAndValue(ref output, NullValue);
      }
      samples_.WriteTo(ref output, _repeated_samples_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (WellId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(WellId);
      }
      if (DataSetId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DataSetId);
      }
      if (CurveName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CurveName);
      }
      if (SampleRate != 0D) {
        size += 1 + 8;
      }
      if (StartDepth != 0D) {
        size += 1 + 8;
      }
      if (CurveType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CurveType);
      }
      if (sampleMeatureId_ != null) {
        size += _single_sampleMeatureId_codec.CalculateSizeWithTag(SampleMeatureId);
      }
      if (sampleUnitId_ != null) {
        size += _single_sampleUnitId_codec.CalculateSizeWithTag(SampleUnitId);
      }
      if (nullValue_ != null) {
        size += _single_nullValue_codec.CalculateSizeWithTag(NullValue);
      }
      size += samples_.CalculateSize(_repeated_samples_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PbWellLogCreateParams other) {
      if (other == null) {
        return;
      }
      if (other.WellId != 0L) {
        WellId = other.WellId;
      }
      if (other.DataSetId != 0L) {
        DataSetId = other.DataSetId;
      }
      if (other.CurveName.Length != 0) {
        CurveName = other.CurveName;
      }
      if (other.SampleRate != 0D) {
        SampleRate = other.SampleRate;
      }
      if (other.StartDepth != 0D) {
        StartDepth = other.StartDepth;
      }
      if (other.CurveType.Length != 0) {
        CurveType = other.CurveType;
      }
      if (other.sampleMeatureId_ != null) {
        if (sampleMeatureId_ == null || other.SampleMeatureId != 0) {
          SampleMeatureId = other.SampleMeatureId;
        }
      }
      if (other.sampleUnitId_ != null) {
        if (sampleUnitId_ == null || other.SampleUnitId != 0) {
          SampleUnitId = other.SampleUnitId;
        }
      }
      if (other.nullValue_ != null) {
        if (nullValue_ == null || other.NullValue != 0D) {
          NullValue = other.NullValue;
        }
      }
      samples_.Add(other.samples_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            WellId = input.ReadInt64();
            break;
          }
          case 16: {
            DataSetId = input.ReadInt64();
            break;
          }
          case 26: {
            CurveName = input.ReadString();
            break;
          }
          case 33: {
            SampleRate = input.ReadDouble();
            break;
          }
          case 41: {
            StartDepth = input.ReadDouble();
            break;
          }
          case 50: {
            CurveType = input.ReadString();
            break;
          }
          case 58: {
            int? value = _single_sampleMeatureId_codec.Read(input);
            if (sampleMeatureId_ == null || value != 0) {
              SampleMeatureId = value;
            }
            break;
          }
          case 66: {
            int? value = _single_sampleUnitId_codec.Read(input);
            if (sampleUnitId_ == null || value != 0) {
              SampleUnitId = value;
            }
            break;
          }
          case 74: {
            double? value = _single_nullValue_codec.Read(input);
            if (nullValue_ == null || value != 0D) {
              NullValue = value;
            }
            break;
          }
          case 82:
          case 81: {
            samples_.AddEntriesFrom(input, _repeated_samples_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            WellId = input.ReadInt64();
            break;
          }
          case 16: {
            DataSetId = input.ReadInt64();
            break;
          }
          case 26: {
            CurveName = input.ReadString();
            break;
          }
          case 33: {
            SampleRate = input.ReadDouble();
            break;
          }
          case 41: {
            StartDepth = input.ReadDouble();
            break;
          }
          case 50: {
            CurveType = input.ReadString();
            break;
          }
          case 58: {
            int? value = _single_sampleMeatureId_codec.Read(ref input);
            if (sampleMeatureId_ == null || value != 0) {
              SampleMeatureId = value;
            }
            break;
          }
          case 66: {
            int? value = _single_sampleUnitId_codec.Read(ref input);
            if (sampleUnitId_ == null || value != 0) {
              SampleUnitId = value;
            }
            break;
          }
          case 74: {
            double? value = _single_nullValue_codec.Read(ref input);
            if (nullValue_ == null || value != 0D) {
              NullValue = value;
            }
            break;
          }
          case 82:
          case 81: {
            samples_.AddEntriesFrom(ref input, _repeated_samples_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PbWellLogCreateList : pb::IMessage<PbWellLogCreateList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PbWellLogCreateList> _parser = new pb::MessageParser<PbWellLogCreateList>(() => new PbWellLogCreateList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PbWellLogCreateList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tet.Transport.Protobuf.Well.WellLogObjectReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbWellLogCreateList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbWellLogCreateList(PbWellLogCreateList other) : this() {
      logList_ = other.logList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbWellLogCreateList Clone() {
      return new PbWellLogCreateList(this);
    }

    /// <summary>Field number for the "log_list" field.</summary>
    public const int LogListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Tet.Transport.Protobuf.Well.PbWellLogCreateParams> _repeated_logList_codec
        = pb::FieldCodec.ForMessage(10, global::Tet.Transport.Protobuf.Well.PbWellLogCreateParams.Parser);
    private readonly pbc::RepeatedField<global::Tet.Transport.Protobuf.Well.PbWellLogCreateParams> logList_ = new pbc::RepeatedField<global::Tet.Transport.Protobuf.Well.PbWellLogCreateParams>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Tet.Transport.Protobuf.Well.PbWellLogCreateParams> LogList {
      get { return logList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PbWellLogCreateList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PbWellLogCreateList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!logList_.Equals(other.logList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= logList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      logList_.WriteTo(output, _repeated_logList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      logList_.WriteTo(ref output, _repeated_logList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += logList_.CalculateSize(_repeated_logList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PbWellLogCreateList other) {
      if (other == null) {
        return;
      }
      logList_.Add(other.logList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            logList_.AddEntriesFrom(input, _repeated_logList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            logList_.AddEntriesFrom(ref input, _repeated_logList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
